/**
 * Hungarian — the board's half.
 *
 * Keyed by the English source sentence, like the server's `i18n/hu.ts`, and holding
 * the **same vocabulary**: utazás / tábla / sáv / javaslat / kártya / tag / szervező
 * / társszervező / tulajdonos / résztvevő / vendég / eldöntve. A noun rendered one
 * way in an error message and another on the button that caused it is what makes a
 * translated app feel assembled rather than made.
 *
 * Three decisions that run through the whole file:
 *
 *  - **informal singular throughout** (`Töltsd ki`, not `Töltse ki`). The English
 *    copy addresses the reader directly and a group trip is not a bank; switching
 *    register halfway would be worse than either choice held to.
 *  - **`{n}` phrases take the singular noun**, because Hungarian puts no plural
 *    after a numeral — `2 tag`, never `2 tagok`. Both the "one" and "many" forms of
 *    a counted phrase therefore translate to the same Hungarian wording, and
 *    `plural()` is what makes that correct rather than lazy.
 *  - **no entry for English**: translating into the source language is the identity.
 *
 * Anything absent falls back to English, which is a safe failure rather than a
 * silent one — `i18n.test.ts` fails on a missing entry, so absence is a decision
 * somebody made, not something nobody noticed.
 */
export const HU_UI_MESSAGES: Readonly<Record<string, string>> = {
  " · {n} not scheduled": " · {n} nincs beütemezve",
  "(you)": "(te)",
  "+ Add card": "+ Új kártya",
  "/person": "/fő",
  "A budget per person?": "Fejenkénti költségkeret?",
  "A feed is configured but the snapshot has not refreshed in days. Every ≈ total in the app is being computed from it.":
    "Be van állítva egy árfolyamforrás, de a mentés napok óta nem frissült. Az alkalmazás minden ≈ összege ebből számol.",
  "Account emails — verifying your address, signing in — are always sent, and these settings never affect them.":
    "A fiókkal kapcsolatos leveleket — cím megerősítése, bejelentkezés — mindig elküldjük, ezek a beállítások nem érintik őket.",
  "Account menu": "Fiók menü",
  "Actions for {card}": "{card} műveletei",
  "Actions for {name}": "{name} műveletei",
  Active: "Aktív",
  Activity: "Előzmények",
  Add: "Hozzáadás",
  "Add reaction": "Reakció hozzáadása",
  "Adding…": "Hozzáadás…",
  "All currencies": "Minden pénznem",
  "Allow several winners": "Több győztes engedélyezése",
  "Almost there": "Már majdnem",
  "Already have an account? {link}": "Van már fiókod? {link}",
  "Also proposed": "További javaslatok",
  Amount: "Összeg",
  Anonymized: "Anonimizált",
  Back: "Vissza",
  "Back to boards": "Vissza a táblákhoz",
  "Back to sign in": "Vissza a bejelentkezéshez",
  "Back to this lane’s own colour": "Vissza a sáv saját színéhez",
  Blocked: "Kitiltva",
  "Board id": "Tábla azonosító",
  Budget: "Költségkeret",
  "Budget per person": "Fejenkénti költségkeret",
  Cancel: "Mégse",
  "Category lanes": "Sávok",
  "Category name": "Sáv neve",
  "Change colour": "Szín módosítása",
  "Changed your mind? Turn it back on in notification settings.":
    "Meggondoltad magad? Az értesítési beállításokban visszakapcsolhatod.",
  Channels: "Csatornák",
  Chat: "Csevegés",
  "Chat, {n} unread": "Csevegés, {n} olvasatlan",
  "Check your inbox": "Nézd meg a postafiókod",
  "Checking what this affects…": "Megnézzük, mit érint ez…",
  "Choose a file": "Fájl választása",
  Clear: "Törlés",
  Close: "Bezárás",
  "Close chat": "Csevegés bezárása",
  "Co-organizer": "Társszervező",
  "Colour for {lane}": "{lane} színe",
  Commit: "Rögzítés",
  Common: "Általános",
  Confirm: "Megerősítés",
  Console: "Konzol",
  Contents: "Tartalom",
  "Continue to sign in": "Tovább a bejelentkezéshez",
  "Continue with Google": "Folytatás Google-fiókkal",
  Contract: "API-szerződés",
  "Copied!": "Kimásolva!",
  "Copy link": "Link másolása",
  Cost: "Költség",
  "Cost is": "A költség",
  "Could not add the category": "A sávot nem sikerült hozzáadni",
  "Could not change email for this board":
    "Az e-mail-beállítást nem sikerült módosítani ezen a táblán",
  "Could not change that": "Ezt nem sikerült módosítani",
  "Could not change the role": "A szerepet nem sikerült módosítani",
  "Could not complete that action": "A műveletet nem sikerült végrehajtani",
  "Could not create the board": "A táblát nem sikerült létrehozni",
  "Could not create the link": "A linket nem sikerült létrehozni",
  "Could not delete": "Nem sikerült törölni",
  "Could not delete the board": "A táblát nem sikerült törölni",
  "Could not delete the category": "A sávot nem sikerült törölni",
  "Could not delete your account. Try again.":
    "A fiókodat nem sikerült törölni. Próbáld újra.",
  "Could not leave this trip": "Nem sikerült kilépni erről az utazásról",
  "Could not lock": "Nem sikerült rögzíteni",
  "Could not open the discussion": "A beszélgetést nem sikerült megnyitni",
  "Could not save changes": "A módosításokat nem sikerült elmenteni",
  "Could not unblock": "A kitiltást nem sikerült visszavonni",
  "Could not unlock": "Nem sikerült feloldani",
  "Could not update this category": "Ezt a sávot nem sikerült módosítani",
  "Could not vote": "Nem sikerült szavazni",
  "Couldn't change the language.": "A nyelvet nem sikerült módosítani.",
  "Couldn't copy — copy the link manually.":
    "Nem sikerült a másolás — másold ki a linket kézzel.",
  "Couldn't join": "Nem sikerült csatlakozni",
  "Couldn't join this board.": "Nem sikerült csatlakozni ehhez a táblához.",
  "Couldn't load chat.": "A csevegést nem sikerült betölteni.",
  "Couldn't load invite links.": "A meghívó linkeket nem sikerült betölteni.",
  "Couldn't load notifications.": "Az értesítéseket nem sikerült betölteni.",
  "Couldn't load the cards. Reload the page to try again.":
    "A kártyákat nem sikerült betölteni. Töltsd újra az oldalt.",
  "Couldn't load the category lanes.": "A sávokat nem sikerült betölteni.",
  "Couldn't load the cost.": "A költséget nem sikerült betölteni.",
  "Couldn't load the crew.": "A csapatot nem sikerült betölteni.",
  "Couldn't load the impact.": "A következményeket nem sikerült betölteni.",
  "Couldn't load the member list.": "A taglistát nem sikerült betölteni.",
  "Couldn't load the trip's decisions. Reload the page to try again.":
    "Az utazás döntéseit nem sikerült betölteni. Töltsd újra az oldalt.",
  "Couldn't load this board's activity.":
    "A tábla előzményeit nem sikerült betölteni.",
  "Couldn't load this board.": "Ezt a táblát nem sikerült betölteni.",
  "Couldn't load your boards.": "A tábláidat nem sikerült betölteni.",
  "Couldn't load your settings.": "A beállításaidat nem sikerült betölteni.",
  "Couldn't read the deployment.": "A telepítést nem sikerült beolvasni.",
  "Couldn't remove the cover. Please try again.":
    "A borítót nem sikerült eltávolítani. Próbáld újra.",
  "Couldn't remove your picture. Please try again.":
    "A képedet nem sikerült eltávolítani. Próbáld újra.",
  "Couldn't run that lookup.": "A keresést nem sikerült lefuttatni.",
  "Couldn't save that name.": "Ezt a nevet nem sikerült elmenteni.",
  "Couldn't save that. Please try again.":
    "Nem sikerült elmenteni. Próbáld újra.",
  "Couldn't upload that cover. Please try again.":
    "A borítót nem sikerült feltölteni. Próbáld újra.",
  "Couldn't upload that picture. Please try again.":
    "A képet nem sikerült feltölteni. Próbáld újra.",
  "Counting…": "Számolás…",
  "Cover image": "Borítókép",
  "Create account": "Fiók létrehozása",
  "Create board": "Tábla létrehozása",
  "Create link": "Link létrehozása",
  "Create one": "Hozz létre egyet",
  "Creating…": "Létrehozás…",
  Crew: "Csapat",
  Currencies: "Pénznemek",
  Currency: "Pénznem",
  "Danger zone": "Veszélyes műveletek",
  Dates: "Dátumok",
  Decided: "Eldöntve",
  "Decided · {name}": "Eldöntve · {name}",
  "Default currency": "Alapértelmezett pénznem",
  Delete: "Törlés",
  "Delete account…": "Fiók törlése…",
  "Delete board": "Tábla törlése",
  "Delete category": "Sáv törlése",
  "Delete message": "Üzenet törlése",
  "Delete my account": "A fiókom törlése",
  "Delete trip": "Utazás törlése",
  "Delete your account": "Fiókod törlése",
  "Delete “{trip}”?": "Törlöd a(z) „{trip}” utazást?",
  "Deletes the trips owned by {account} and rebuilds the published demo board from the seed — five members, fourteen options, four decisions, the chat and the votes. No other account is touched, and the demo password is reset to the one in the README.":
    "Törli a(z) {account} tulajdonában lévő utazásokat, és újraépíti a nyilvános demó táblát: öt tag, tizennégy javaslat, négy döntés, a csevegés és a szavazatok. Más fiókot nem érint, a demó jelszava pedig visszaáll a README-ben szereplőre.",
  "Deleting your account removes your personal data for good. Boards you own pass to another member, or are deleted if you're the only one on them — the next screen names them before anything happens.":
    "A fiók törlése véglegesen eltávolítja a személyes adataidat. A tulajdonodban lévő táblák átszállnak egy másik tagra, vagy törlődnek, ha egyedül vagy rajtuk — a következő képernyő felsorolja őket, mielőtt bármi történne.",
  "Deleting…": "Törlés…",
  "Deletion impact": "A törlés következményei",
  "Demo data": "Demó adatok",
  "Demo rebuilt.": "A demó újraépült.",
  Destination: "Úti cél",
  Disable: "Kikapcsolás",
  Disabled: "Kikapcsolva",
  Discuss: "Megbeszélés",
  Discussion: "Beszélgetés",
  "Dismiss notification": "Értesítés elvetése",
  "Drag to reorder the {lane} lane": "Fogd meg a(z) {lane} sáv átrendezéséhez",
  "Drag {card} — reorder or drop on Decided to lock":
    "Fogd meg: {card} — rendezd át, vagy húzd az Eldöntve sávra a rögzítéshez",
  "Draw the options still being decided, under the ones that are settled.":
    "Mutasd a még eldöntendő javaslatokat is, az eldöntöttek alatt.",
  "Drop here to decide": "Húzd ide a döntéshez",
  "Drop here to lock": "Húzd ide a rögzítéshez",
  "Drop to decide": "Húzd ide a döntéshez",
  Edit: "Szerkesztés",
  "Edit option": "Javaslat szerkesztése",
  "Edit trip": "Utazás szerkesztése",
  "Edit trip details": "Utazás adatainak szerkesztése",
  Email: "E-mail",
  "Email (optional)": "E-mail (nem kötelező)",
  "Email me when I'm @mentioned": "Kapjak e-mailt, ha @megemlítenek",
  "Email queue": "E-mail várólista",
  "Email verified": "E-mail megerősítve",
  "Email, name, or user id": "E-mail, név vagy felhasználói azonosító",
  "End time": "Befejezés időpontja",
  "Ended trip boards": "Befejezett utazások",
  Environment: "Környezet",
  "Everyone on the trip": "Az utazás minden tagja",
  "Everyone on this trip sees the colour you pick.":
    "A választott színt az utazás minden tagja látja.",
  "Exchange rates": "Árfolyamok",
  "Existing links": "Meglévő linkek",
  Failed: "Sikertelen",
  Fetched: "Letöltve",
  Find: "Keresés",
  "Fill in the fields marked with *": "Töltsd ki a *-gal jelölt mezőket",
  "Find a user": "Felhasználó keresése",
  "Full at {cap} options — remove one to add another.":
    "Betelt, {cap} javaslat van benne — törölj egyet, ha újat szeretnél.",
  "Give these dates and they'll take their place on the trip. ":
    "Add meg ezeket a dátumokat, és bekerülnek az utazás menetébe. ",
  Global: "Általános",
  "Google only": "Csak Google",
  "Google sign-in didn't complete. Your browser may be blocking cookies set by the API — try again, or sign in with your email and password.":
    "A Google-bejelentkezés nem fejeződött be. Lehet, hogy a böngésződ blokkolja az API sütijeit — próbáld újra, vagy jelentkezz be e-mail-címmel és jelszóval.",
  "Group Trip Planner": "Group Trip Planner",
  Guest: "Vendég",
  History: "Lezárva",
  "I'm in": "Én jövök",
  Invite: "Meghívás",
  "Invite people to this board": "Hívj meg másokat erre a táblára",
  "It may have been mistyped or truncated by your mail app. Nothing changed — you can turn mention emails off from notification settings instead.":
    "Elképzelhető, hogy elírták, vagy a levelezőprogramod levágta. Semmi nem változott — a megemlítési értesítőket az értesítési beállításokban is kikapcsolhatod.",
  "Joining board…": "Csatlakozás a táblához…",
  "Keep only one winner": "Csak egy győztes lehet",
  "Know them already? The Dates lane will start decided. Skip to let the group vote on it.":
    "Már tudod őket? Akkor a Dátumok sáv eldöntve indul. Hagyd ki, ha a csapat szavazzon róla.",
  Language: "Nyelv",
  "Last seen": "Utoljára láttuk",
  "Leave this trip? You'll lose access unless re-invited.":
    "Kilépsz erről az utazásról? Új meghívó nélkül elveszíted a hozzáférést.",
  "Leave trip": "Kilépés az utazásból",
  "Leave “{trip}”?": "Kilépsz a(z) „{trip}” utazásból?",
  "Leaving…": "Kilépés…",
  Link: "Link",
  "Link type": "Link típusa",
  "Link ↗": "Link ↗",
  "Lisbon 2026": "Lisszabon 2026",
  "Lisbon, Portugal": "Lisszabon, Portugália",
  "Load older": "Korábbiak betöltése",
  "Load older messages": "Korábbi üzenetek betöltése",
  "Loading activity…": "Előzmények betöltése…",
  "Loading board…": "Tábla betöltése…",
  "Loading cards…": "Kártyák betöltése…",
  "Loading crew…": "Csapat betöltése…",
  "Loading decisions…": "Döntések betöltése…",
  "Loading lanes…": "Sávok betöltése…",
  "Loading links…": "Linkek betöltése…",
  "Loading messages…": "Üzenetek betöltése…",
  "Loading your boards": "Tábláid betöltése",
  "Loading your boards…": "Tábláid betöltése…",
  "Loading your settings…": "Beállításaid betöltése…",
  "Loading…": "Betöltés…",
  "Lock a priced option to start the tally.":
    "Rögzíts egy árazott javaslatot, és elindul az összesítés.",
  "Lock card": "Kártya rögzítése",
  "Log out": "Kijelentkezés",
  "Looking…": "Keresés…",
  "Make owner": "Tulajdonossá tesz",
  "Mark all read": "Összes megjelölése olvasottként",
  "Mark verified": "Megerősítettnek jelöl",
  "Marked verified.": "Megerősítettnek jelölve.",
  Members: "Tagok",
  "Members & roles": "Tagok és szerepek",
  Message: "Üzenet",
  "Message the group… @ to mention": "Írj a csapatnak… @ a megemlítéshez",
  Messages: "Üzenetek",
  "Move to Decided": "Áthelyezés az Eldöntve sávba",
  "Multi-day": "Több napos",
  "Mute email": "E-mailek némítása",
  Name: "Név",
  "New board · {step} of {total}": "Új tábla · {step}/{total}",
  "New category name": "Új sáv neve",
  Next: "Tovább",
  "Next month": "Következő hónap",
  "No account? {link}": "Nincs még fiókod? {link}",
  "No committed cost": "Nincs rögzített költség",
  "No dates chosen": "Nincs dátum kiválasztva",
  "No destination yet": "Még nincs úti cél",
  "No feed configured — conversion is off, and every dashboard reports exact per-currency figures only. This is a valid deployment.":
    "Nincs árfolyamforrás beállítva — az átváltás ki van kapcsolva, és minden áttekintő csak a pontos, pénznem szerinti összegeket mutatja. Ez érvényes beállítás.",
  "No image yet": "Még nincs kép",
  "No links yet. Create one above.":
    "Még nincs link. Hozz létre egyet fentebb.",
  "No mail has been queued for this account.":
    "Ehhez a fiókhoz nem került levél a várólistára.",
  "No messages yet. Say hello — or @mention someone to pull them in.":
    "Még nincs üzenet. Köszönj be — vagy @említs valakit, hogy bekapcsolódjon.",
  "No need to wait around, though. If someone has already invited you to their board you can join it right now, and propose, vote and chat like everyone else.":
    "Várni viszont nem kell. Ha valaki már meghívott a táblájára, most azonnal csatlakozhatsz, és ugyanúgy javasolhatsz, szavazhatsz és cseveghetsz, mint bárki más.",
  "No options yet": "Még nincs javaslat",
  "No provider key set — mail is logged to the console, not sent.":
    "Nincs szolgáltatói kulcs beállítva — a levelek a konzolra kerülnek, nem mennek ki.",
  "Nobody matches “{query}”.": "Senki nem felel meg ennek: „{query}”.",
  Node: "Node",
  "Not on the timeline": "Nincs az idővonalon",
  Notes: "Megjegyzések",
  "Nothing has been done from this console yet.":
    "Erről a konzolról még semmi nem történt.",
  "Nothing has happened here yet. Locked decisions, role changes, and departures will show up on this list.":
    "Itt még semmi nem történt. A rögzített döntések, szerepváltások és kilépések ezen a listán jelennek meg.",
  "Nothing here has dates yet. Add dates to a decision and it will appear on the trip's calendar.":
    "Itt még semminek nincs dátuma. Adj dátumot egy döntéshez, és megjelenik az utazás naptárában.",
  "Nothing is decided yet. Lock an option on the board and it lands here.":
    "Még semmi nincs eldöntve. Rögzíts egy javaslatot a táblán, és ide kerül.",
  "Nothing was decided here": "Itt nem dőlt el semmi",
  "Nothing yet. Proposals, decisions and mentions land here.":
    "Még semmi. A javaslatok, döntések és megemlítések ide kerülnek.",
  "Notification settings": "Értesítési beállítások",
  Notifications: "Értesítések",
  "Now pick the end": "Most válaszd ki a végét",
  "Nowhere booked for this night": "Erre az éjszakára nincs szállás",
  Off: "Ki",
  "Offline — not updating": "Nincs kapcsolat — nem frissül",
  On: "Be",
  "One thing first: starting a board needs a confirmed email address. We've sent a link to {email} — open it and you're set. (Check the spam folder if it's taking its time.)":
    "Egy dolog még: tábla indításához megerősített e-mail-cím kell. Küldtünk egy linket ide: {email} — nyisd meg, és készen vagy. (Ha késik, nézd meg a spam mappát is.)",
  "Only whoever's in": "Csak aki jön",
  "Operations · signed in as {email}": "Üzemeltetés · bejelentkezve: {email}",
  "Operator log": "Üzemeltetői napló",
  Options: "Javaslatok",
  "Outside the trip's dates": "Az utazás dátumain kívül",
  "Over budget": "Túllépi a keretet",
  "Overlaps another {lane} decision":
    "Átfedésben van egy másik {lane} döntéssel",
  Owner: "Tulajdonos",
  "Ownership transfers ({n})": "Tulajdonjog átszáll ({n})",
  Palettes: "Színpaletták",
  Participant: "Résztvevő",
  Password: "Jelszó",
  Pending: "Várakozik",
  "Per person": "Fejenként",
  "Permanently deleted ({n})": "Véglegesen törölve ({n})",
  Personal: "Személyes",
  "Pick a start, then an end": "Válaszd ki a kezdetet, majd a végét",
  "Pick both days, or skip this step.":
    "Válaszd ki mindkét napot, vagy hagyd ki ezt a lépést.",
  Plan: "Terv",
  "Previous month": "Előző hónap",
  "Priced for": "Az ára erre szól:",
  "Priced for part of the group": "A csapat egy részére szóló ár",
  "Profile picture": "Profilkép",
  Progress: "Állapot",
  "Propose an option": "Javaslat beküldése",
  "Propose option": "Javaslat beküldése",
  Proposed: "Javasolva",
  "Proposed by": "Beküldte",
  Published: "Közzétéve",
  "React {emoji}": "Reakció: {emoji}",
  "Reading the deployment…": "A telepítés beolvasása…",
  "Reading…": "Beolvasás…",
  "Rebuild the demo trip": "Demó utazás újraépítése",
  "Rebuilding…": "Újraépítés…",
  "Redeeming your invite.": "Meghívó beváltása.",
  Refresh: "Frissítés",
  Reload: "Újratöltés",
  "Reload the board": "Tábla újratöltése",
  Remove: "Eltávolítás",
  "Remove from trip": "Eltávolítás az utazásból",
  "Removing…": "Eltávolítás…",
  "Rename {lane}": "{lane} átnevezése",
  "Reorder {trip}": "{trip} átrendezése",
  Replaced: "Lecserélve",
  "Resend verification": "Megerősítő levél újraküldése",
  Retry: "Újra",
  "Role granted": "Szerep megadva",
  Save: "Mentés",
  "Save changes": "Módosítások mentése",
  "Save option": "Javaslat mentése",
  "Saved. Everyone on your boards sees the new name.":
    "Elmentve. A tábláidon mindenki az új nevet látja.",
  "Saving…": "Mentés…",
  Send: "Küldés",
  Sending: "Küldés folyamatban",
  Sent: "Elküldve",
  Settings: "Beállítások",
  "Show proposals": "Javaslatok mutatása",
  "Showing the first {n} day — something is dated much further out than the rest.":
    "Csak az első {n} napot mutatjuk — valami sokkal későbbre van dátumozva, mint a többi.",
  "Showing the first {n} days — something is dated much further out than the rest.":
    "Csak az első {n} napot mutatjuk — valami sokkal későbbre van dátumozva, mint a többi.",
  "Shown wherever you appear — the crew list and board chat. Without one, your initials stand in.":
    "Ott jelenik meg, ahol te is — a csapatlistában és a tábla csevegésében. Ha nincs, a monogramod helyettesíti.",
  "Sign in": "Bejelentkezés",
  "Sign-in": "Bejelentkezés",
  "Signed up": "Regisztrált",
  "Signing in…": "Bejelentkezés…",
  Skip: "Kihagyom",
  "Some of these fall outside the trip's own dates.":
    "Ezek közül néhány az utazás dátumain kívül esik.",
  Someone: "Valaki",
  "Someone naming you in a board's chat sends you an email. Turn this off and mentions still show up in the app.":
    "Ha valaki megnevez egy tábla csevegésében, e-mailt kapsz róla. Ha kikapcsolod, a megemlítések akkor is megjelennek az alkalmazásban.",
  "Something broke on this page": "Valami elromlott ezen az oldalon",
  "Something went wrong": "Valami hiba történt",
  Source: "Forrás",
  "Still to spend": "Még elkölthető",
  "Start time": "Kezdés időpontja",
  Target: "Cél",
  "That board doesn't exist or you're not a member.":
    "Ez a tábla nem létezik, vagy nem vagy a tagja.",
  "That didn't work.": "Ez nem sikerült.",
  "That link didn't work": "Ez a link nem működött",
  "That start date has already passed.": "Ez a kezdődátum már elmúlt.",
  "That's further ahead than a trip can be planned.":
    "Ez messzebb van, mint ameddig egy utazás előre tervezhető.",
  "The Dates lane starts with this already decided — unlock it any time to let the group pick instead.":
    "A Dátumok sáv ezzel eldöntve indul — bármikor feloldhatod, és akkor a csapat dönt.",
  "The card gets an {control} button, and its cost is split between the people who press it — nobody else pays for it. Everyone can see who is in.":
    "A kártyára kerül egy {control} gomb, és a költséget azok osztják el, akik megnyomják — más nem fizet érte. Azt is látja mindenki, ki jön.",
  "The error has been recorded. Reloading usually clears it — your trips and decisions are stored on the server, so nothing was lost.":
    "A hibát rögzítettük. Az újratöltés általában megoldja — az utazásaid és döntéseid a szerveren vannak, tehát semmi nem vesztett el.",
  "The last day can't come before the first.":
    "Az utolsó nap nem lehet korábban, mint az első.",
  "This app is in {language}. It is the only language available so far.":
    "Ez az alkalmazás {language} nyelven van. Egyelőre csak ez a nyelv érhető el.",
  "This board changed since you opened it. Reload to see the latest, then re-apply your edit.":
    "Ez a tábla megváltozott, mióta megnyitottad. Töltsd újra a legfrissebb állapothoz, majd írd be újra a módosításodat.",
  "This board has ended — it's now read-only. Proposing, dot-voting, and locking are closed.":
    "Ez a tábla lezárult — mostantól csak olvasható. A javaslás, a szavazás és a rögzítés le van zárva.",
  "This deployment": "Ez a telepítés",
  "This deployment has no console configured for you.":
    "Ebben a telepítésben nincs konzol beállítva neked.",
  "This link is invalid or has expired. Sign in to request a new one.":
    "Ez a link érvénytelen vagy lejárt. Jelentkezz be, és kérj újat.",
  "This permanently deletes your account and personal data. It can't be undone.":
    "Ez véglegesen törli a fiókodat és a személyes adataidat. Nem vonható vissza.",
  "This permanently removes the board and its membership for everyone. This can't be undone.":
    "Ez véglegesen törli a táblát és mindenki tagságát. Nem vonható vissza.",
  "This throws away whatever visitors have done to the demo, and cannot be undone.":
    "Ez eldobja mindazt, amit a látogatók a demóval tettek, és nem vonható vissza.",
  "This trip's dates aren't settled yet, so the days below are drawn from the options themselves and will shift as they change. Lock a date to frame the trip.":
    "Az utazás dátumai még nincsenek eldöntve, ezért az alábbi napok magukból a javaslatokból adódnak, és velük együtt mozdulnak. Rögzíts egy dátumot, hogy az utazás keretet kapjon.",
  Timeline: "Idővonal",
  Title: "Cím",
  "To silence a single noisy board, open it and use {control} in its ⋯ menu.":
    "Ha egyetlen zajos táblát szeretnél elhallgattatni, nyisd meg, és használd a {control} lehetőséget a ⋯ menüjében.",
  "Total for the group": "A csapat összköltsége",
  "Transfer ownership": "Tulajdonjog átadása",
  Trip: "Utazás",
  "Trip Board": "Utazástábla",
  "Trip Board — your boards": "Utazástábla — a tábláid",
  "Trip chat": "Utazás csevegése",
  "Trip menu": "Utazás menü",
  "Trip view": "Nézet",
  "Trip name": "Utazás neve",
  Trips: "Utazások",
  "Try again": "Próbáld újra",
  Unblock: "Kitiltás visszavonása",
  Unlock: "Feloldás",
  Unverified: "Nem megerősített",
  "Up since": "Fut ekkortól",
  "Uploading…": "Feltöltés…",
  Uploads: "Feltöltések",
  Used: "Felhasználva",
  Users: "Felhasználók",
  "Verification email sent.": "Megerősítő levél elküldve.",
  "Verification failed": "A megerősítés nem sikerült",
  Verified: "Megerősítve",
  "Verifying…": "Megerősítés…",
  "View details": "Részletek",
  Volume: "Mennyiség",
  Votes: "Szavazatok",
  "We won't email you when someone @mentions you. You'll still see mentions in the app, and account emails — verifying your address, signing in — are unaffected.":
    "Nem küldünk e-mailt, ha valaki @megemlít. A megemlítéseket az alkalmazásban továbbra is látod, a fiókkal kapcsolatos leveleket — cím megerősítése, bejelentkezés — pedig ez nem érinti.",
  "What are prices quoted in?": "Milyen pénznemben vannak az árak?",
  "What's the trip called?": "Mi az utazás neve?",
  When: "Mikor",
  "When?": "Mikor?",
  "Where are you going?": "Hová mentek?",
  "Where it goes": "Mire megy el",
  "Yes, rebuild it": "Igen, épüljön újra",
  "You don't own any boards.": "Nincs saját táblád.",
  "You're unsubscribed": "Leiratkoztál",
  "Your picture": "A képed",
  "Your settings": "A beállításaid",
  "Your trip boards": "Az utazástábláid",
  "barred from rejoining": "nem csatlakozhat újra",
  "email, name, or user id": "e-mail, név vagy felhasználói azonosító",
  "https://…": "https://…",
  in: "jön",
  "just now": "épp most",
  "message deleted": "üzenet törölve",
  "no bed booked": "nincs lefoglalt szállás",
  "no rate to add these up with":
    "nincs árfolyam, amivel ezeket összeadhatnánk",
  "no votes": "nincs szavazat",
  "nobody yet": "még senki",
  "not sent": "nincs elküldve",
  "nothing planned": "nincs terv",
  "nothing — there was no demo trip here": "semmit — itt nem volt demó utazás",
  or: "vagy",
  "outside the trip's dates": "az utazás dátumain kívül",
  "per person": "fejenként",
  "to spare": "marad",
  "voted before the last change": "a legutóbbi módosítás előtt szavazott",
  "your address": "a címed",
  "yours: ": "a tiéd: ",
  "{actor} deleted {author}'s message": "{actor} törölte {author} üzenetét",
  "{amount} per person": "{amount} fejenként",
  "{cap} categories is the maximum. Delete one to add another.":
    "Legfeljebb {cap} sáv lehet. Törölj egyet, ha újat szeretnél.",
  "{card} — edit option": "{card} — javaslat szerkesztése",
  "{card} — view details": "{card} — részletek",
  "{currencies} not converted": "{currencies} nincs átváltva",
  "{currencies} not counted — no rate to convert with":
    "{currencies} nincs beszámítva — nincs árfolyam az átváltáshoz",
  "{date}: {count}": "{date}: {count}",
  "{emoji} {n}": "{emoji} {n}",
  "{kind} — a single-use link for one person, optionally emailed. Used up after the first join.":
    "{kind} — egyszer használható link egy személynek, e-mailben is elküldhető. Az első csatlakozás után elhasználódik.",
  "{kind} — one reusable link anyone can use to join. One per role; disable it anytime (members who joined stay).":
    "{kind} — egy újrahasználható link, amivel bárki csatlakozhat. Szerepenként egy; bármikor kikapcsolhatod (a már csatlakozott tagok maradnak).",
  "{label} — choose a file": "{label} — válassz fájlt",
  "{lane} lane actions": "{lane} sáv műveletei",
  "{lane} — rename category": "{lane} — sáv átnevezése",
  "{name} deleted their message": "{name} törölte a saját üzenetét",
  "{n} attempt": "{n} kísérlet",
  "{n} attempts": "{n} kísérlet",
  "{n} decision pending": "{n} döntés várakozik",
  "{n} decision placed": "{n} döntés elhelyezve",
  "{n} decisions pending": "{n} döntés várakozik",
  "{n} decisions placed": "{n} döntés elhelyezve",
  "{n} in": "{n} jön",
  "{n} in — see who": "{n} jön — nézd meg, kik",
  "{n} job claimed longer ago than the reclaim window — a worker probably died mid-send.":
    "{n} feladat régebben van lefoglalva, mint a visszaigénylési idő — valószínűleg elhalt egy feldolgozó küldés közben.",
  "{n} jobs claimed longer ago than the reclaim window — a worker probably died mid-send.":
    "{n} feladat régebben van lefoglalva, mint a visszaigénylési idő — valószínűleg elhalt egy feldolgozó küldés közben.",
  "{n} member": "{n} tag",
  "{n} members": "{n} tag",
  "{n} night": "{n} éjszaka",
  "{n} nights": "{n} éjszaka",
  "{n} signups in the last 30 days": "{n} regisztráció az elmúlt 30 napban",
  "{n} unread": "{n} olvasatlan",
  "{n} vote — see who": "{n} szavazat — nézd meg, kik",
  "Everyone has voted.": "Mindenki szavazott.",
  "Everyone is in.": "Mindenki benne van.",
  "Not in yet": "Még nem jelezte",
  "Yet to vote": "Még nem szavazott",
  "{n} / {total} in": "{n} / {total} benne",
  "{n} / {total} voted": "{n} / {total} szavazott",
  "{n} voted": "{n} szavazott",
  "{n} votes — see who": "{n} szavazat — nézd meg, kik",
  "{trip} — you're the only member": "{trip} — egyedül te vagy a tagja",
  "· outside the trip’s dates": "· az utazás dátumain kívül",
  "· 🔕 Email muted": "· 🔕 E-mailek némítva",
  "— exactly {amount}": "— pontosan {amount}",
  "○ Vote": "○ Szavazok",
  "● Voted": "● Megszavaztam",
  "☀ Light mode": "☀ Világos mód",
  "☾ Dark mode": "☾ Sötét mód",
  "⚙ Console": "⚙ Konzol",
  "🔔 Unmute email": "🔔 E-mailek visszakapcsolása",
  "🔕 Mute email": "🔕 E-mailek némítása",
  "＋ Add category": "＋ Új sáv",
  "＋ New board": "＋ Új tábla",
  "＋ Propose the first option": "＋ Küldd be az első javaslatot",
  "Make {name} the owner? You'll become a co-organizer, and only they can hand it back.":
    "Legyen {name} a tulajdonos? Te társszervező leszel, és csak ő adhatja vissza.",
  "Remove and block": "Eltávolítás és tiltás",
  "Remove {name} and block them? They won't be able to rejoin, even with an invite link.":
    "Eltávolítod és letiltod őt: {name}? Nem tud majd visszalépni, meghívó linkkel sem.",
  "Remove {name} from this trip? You can invite them back.":
    "Eltávolítod őt az útról: {name}? Később újra meghívhatod.",
  "Role for {name}": "{name} szerepköre",
  "They lose access and can't rejoin, even with a link.":
    "Elveszíti a hozzáférést, és linkkel sem tud visszalépni.",
  "They lose access. You can invite them back.":
    "Elveszíti a hozzáférést. Később újra meghívhatod.",
  "They take over the trip and you become a co-organizer.":
    "Ő veszi át az utat, te pedig társszervező leszel.",
  "Nothing found — you can write it in yourself.":
    "Nincs találat — beírhatod magad is.",
  "Start typing to search, or write anywhere you like.":
    "Kezdj írni a kereséshez, vagy írj be bármit.",
  "Place names from {source}, CC BY 4.0": "Helynévadatok: {source}, CC BY 4.0",
  "Place list": "Helyek listája",
  "Loads the destination suggestions — every populated place over 5,000 people, every region and every country — from the dataset shipped with this build. Needed once per environment; nothing else uses it and nothing depends on it, so re-running is safe. Until it has run, the destination field on the create-trip form simply offers nothing.":
    "Betölti az úticél-javaslatokat — minden 5000 főnél nagyobb települést, minden régiót és országot — a buildéel szállított adathalmazból. Környezetenként egyszer kell; semmi más nem használja és semmi nem függ tőle, így újra futtatni is biztonságos. Amíg le nem fut, az új utazás űrlap úticél mezője nem kínál semmit.",
  "Loading places…": "Helyek betöltése…",
  "Load the place list": "Helyek listájának betöltése",
  "Writing tens of thousands of rows — this takes a few seconds.":
    "Tízezernyi sor írása — ez elég néhány másodpercet vesz igénybe.",
  "Places loaded.": "A helyek betöltődtek.",
  Places: "Helyek",
  "Account suspended.": "A fiók felfüggesztve.",
  "Ends on": "Eddig tart",
  "Lift suspension": "Felfüggesztés feloldása",
  Permanent: "Végleges",
  "Pick an end date, or choose permanent.":
    "Válassz záró dátumot, vagy jelöld véglegesnek.",
  "Reason given": "Megadott indok",
  "Say why — the person is shown this.":
    "Írd le az indokot — ezt látja majd az érintett.",
  Suspend: "Felfüggesztés",
  "Suspend account": "Fiók felfüggesztése",
  Suspended: "Felfüggesztve",
  "Suspended until": "Felfüggesztve eddig",
  "Suspending…": "Felfüggesztés…",
  "Suspension lifted.": "A felfüggesztés feloldva.",
  "Was suspended": "Fel volt függesztve",
  "Was suspended until": "Eddig volt felfüggesztve",
  "Why this account is being suspended": "Miért függeszted fel ezt a fiókot",
  "Any trip they own passes to a co-organizer, or to the longest-standing participant. A trip with nobody else on it is deleted, with everything in it.":
    "A saját utazásai átszállnak egy társszervezőre, vagy a leghosszabb ideje csatlakozott résztvevőre. Az az utazás, amelyen rajta kívül nincs senki, mindenestül törlődik.",
  "Delete account": "Fiók törlése",
  "Erasing…": "Törlés…",
  "Their proposals and messages in other people's trips stay, credited to “Deleted user”. This cannot be undone.":
    "A más utazásaiban tett javaslatai és üzenetei megmaradnak, „Deleted user” néven. Ez nem vonható vissza.",
  "They owned no trips.": "Nem volt saját utazása.",
  "Yes, erase this account": "Igen, töröljük ezt a fiókot",
  "{email} is erased.": "{email} törölve.",
  "{trip} → {name}": "{trip} → {name}",
  "{trip} — deleted": "{trip} — törölve",
  "Delete “{lane}”?": "Törlöd a(z) „{lane}” sávot?",
  "This removes the lane and every card in it. This can’t be undone.":
    "Ez eltávolítja a sávot és minden kártyáját. Ez nem vonható vissza.",
  "Crew — manage members and roles": "Csapat — tagok és szerepkörök kezelése",
  "Crew — see members and roles": "Csapat — tagok és szerepkörök megtekintése",
  "Guests — not asked to vote": "Vendégek — őket nem kérdezzük",
  "Guests — not asked to join": "Vendégek — ők nem csatlakoznak",
  Lane: "Sáv",
  "Propose something at {time} on {day}": "Javasolj valamit ide: {day} {time}",
  "Still being decided": "Még döntés alatt",
  "No dates yet": "Még nincs dátum",
  "No price yet": "Még nincs ár",
  "split between whoever’s in": "a résztvevők között elosztva",
  "for {n} person on the trip": "{n} főre az utazáson",
  "for {n} people on the trip": "{n} főre az utazáson",
  "edited since": "azóta szerkesztve",
  "Nobody has voted for this yet.": "Erre még senki nem szavazott.",
  "Nobody is in yet.": "Még senki sem jelentkezett.",
  "Who’s in": "Ki tart velünk",
  "outside the trip’s dates": "az utazás dátumain kívül",
  "A lowercase letter": "Egy kisbetű",
  "A number": "Egy számjegy",
  "A special character": "Egy speciális karakter",
  "An uppercase letter": "Egy nagybetű",
  "At least {n} characters": "Legalább {n} karakter",
  "Done:": "Kész:",
  "Hide password": "Jelszó elrejtése",
  Nickname: "Becenév",
  "No sign of it? Have a look in your spam folder — it likes to hide there.":
    "Nem találod? Nézd meg a spam mappát is — szeret ott megbújni.",
  Normal: "Közepes",
  "Password again": "Jelszó még egyszer",
  "Show password": "Jelszó megjelenítése",
  "Still needed:": "Még hiányzik:",
  Strong: "Erős",
  "We've sent you a link to verify your email address.":
    "Küldtünk egy linket az e-mail-címed megerősítéséhez.",
  Weak: "Gyenge",
  "Your password needs": "A jelszavadhoz kell",
  "Welcome on board! :)": "Üdv a fedélzeten! :)",
};
