/**
 * Hungarian — the board's half.
 *
 * Keyed by the English source sentence, like the server's `i18n/hu.ts`, and holding
 * the **same vocabulary**: utazás / tábla / sáv / javaslat / kártya / tag / szervező
 * / társszervező / tulajdonos / résztvevő / vendég / eldöntve. A noun rendered one
 * way in an error message and another on the button that caused it is what makes a
 * translated app feel assembled rather than made.
 *
 * Three decisions that run through the whole file:
 *
 *  - **informal singular throughout** (`Töltsd ki`, not `Töltse ki`). The English
 *    copy addresses the reader directly and a group trip is not a bank; switching
 *    register halfway would be worse than either choice held to.
 *  - **`{n}` phrases take the singular noun**, because Hungarian puts no plural
 *    after a numeral — `2 tag`, never `2 tagok`. Both the "one" and "many" forms of
 *    a counted phrase therefore translate to the same Hungarian wording, and
 *    `plural()` is what makes that correct rather than lazy.
 *  - **no entry for English**: translating into the source language is the identity.
 *
 * Anything absent falls back to English, which is a safe failure rather than a
 * silent one — `i18n.test.ts` fails on a missing entry, so absence is a decision
 * somebody made, not something nobody noticed.
 */
export const HU_UI_MESSAGES: Readonly<Record<string, string>> = {
  " · {n} not scheduled": " · {n} nincs beütemezve",
  "(you)": "(te)",
  "+ Add card": "+ Új kártya",
  "/person": "/fő",
  "A feed is configured but the snapshot has not refreshed in days. Every ≈ total in the app is being computed from it.":
    "Be van állítva egy árfolyamforrás, de a mentés napok óta nem frissült. Az alkalmazás minden ≈ összege ebből számol.",
  "Account emails are always sent, and these settings never affect them. That covers verifying your address and signing in.":
    "A fiókkal kapcsolatos leveleket mindig elküldjük, és ezek a beállítások nem érintik őket. Ilyen a cím megerősítése és a bejelentkezés.",
  "Account menu": "Fiók menü",
  "Actions for {card}": "{card} műveletei",
  "Actions for {name}": "{name} műveletei",
  Activity: "Előzmények",
  Add: "Hozzáadás",
  "Add reaction": "Reakció hozzáadása",
  "Adding…": "Hozzáadás…",
  "All currencies": "Minden pénznem",
  "Allow multi-select": "Többszörös választás engedélyezése",
  "Allow single-select": "Egyszeres választás engedélyezése",
  "Almost there": "Már majdnem",
  "Already have an account? {link}": "Van már fiókod? {link}",
  "Also proposed": "További javaslatok",
  Amount: "Összeg",
  Anonymized: "Anonimizált",
  Back: "Vissza",
  "Back to boards": "Vissza a táblákhoz",
  "Back to sign in": "Vissza a bejelentkezéshez",
  "Back to this lane’s own colour": "Vissza a sáv saját színéhez",
  Blocked: "Kitiltva",
  "Board id": "Tábla azonosító",
  Budget: "Költségkeret",
  "Budget per person": "Fejenkénti költségkeret",
  Cancel: "Mégse",
  Colour: "Szín",
  "Category lanes": "Sávok",
  "Category name": "Sáv neve",
  "Change colour": "Szín módosítása",
  "Changed your mind? Turn it back on in notification settings.":
    "Meggondoltad magad? Az értesítési beállításokban visszakapcsolhatod.",
  Channels: "Csatornák",
  Chat: "Csevegés",
  "Chat, {n} unread": "Csevegés, {n} olvasatlan",
  "Check your inbox": "Nézd meg a postafiókod",
  "Checking what this affects…": "Megnézzük, mit érint ez…",
  "Choose a file": "Fájl választása",
  Clear: "Törlés",
  Close: "Bezárás",
  "Close chat": "Csevegés bezárása",
  "Collapse {trip} to a bubble": "{trip} csevegésének összecsukása buborékba",
  "Colour for {lane}": "{lane} színe",
  Commit: "Rögzítés",
  Common: "Általános",
  Confirm: "Megerősítés",
  Console: "Konzol",
  Contents: "Tartalom",
  "Continue to sign in": "Tovább a bejelentkezéshez",
  "Continue with Google": "Folytatás Google-fiókkal",
  Contract: "API-szerződés",
  "Copied!": "Kimásolva!",
  "Copy link": "Link másolása",
  Cost: "Költség",
  "Cost is": "A költség",
  "Could not add the category": "A sávot nem sikerült hozzáadni",
  "Could not change email for this board":
    "Az e-mail-beállítást nem sikerült módosítani ezen a táblán",
  "Could not change that": "Ezt nem sikerült módosítani",
  "Could not change the role": "A szerepet nem sikerült módosítani",
  "Could not complete that action": "A műveletet nem sikerült végrehajtani",
  "Could not create the board": "A táblát nem sikerült létrehozni",
  "Could not create the link": "A linket nem sikerült létrehozni",
  "Could not delete": "Nem sikerült törölni",
  "Could not delete the board": "A táblát nem sikerült törölni",
  "Could not delete the category": "A sávot nem sikerült törölni",
  "Could not delete your account. Try again.":
    "A fiókodat nem sikerült törölni. Próbáld újra.",
  "Could not leave this trip": "Nem sikerült kilépni erről az utazásról",
  "Could not lock": "Nem sikerült rögzíteni",
  "Could not open the discussion": "A beszélgetést nem sikerült megnyitni",
  "Could not save changes": "A módosításokat nem sikerült elmenteni",
  "Could not unblock": "A kitiltást nem sikerült visszavonni",
  "Could not unlock": "Nem sikerült feloldani",
  "Could not update this category": "Ezt a sávot nem sikerült módosítani",
  "Could not vote": "Nem sikerült szavazni",
  "Couldn't change the language.": "A nyelvet nem sikerült módosítani.",
  "Couldn't copy. Copy the link manually.":
    "Nem sikerült a másolás. Másold ki a linket kézzel.",
  "Couldn't join": "Nem sikerült csatlakozni",
  "Couldn't join this board.": "Nem sikerült csatlakozni ehhez a táblához.",
  "Couldn't load chat.": "A csevegést nem sikerült betölteni.",
  "Couldn't load invite links.": "A meghívó linkeket nem sikerült betölteni.",
  "Couldn't load notifications.": "Az értesítéseket nem sikerült betölteni.",
  "Couldn't load the cards. Reload the page to try again.":
    "A kártyákat nem sikerült betölteni. Töltsd újra az oldalt.",
  "Couldn't load the category lanes.": "A sávokat nem sikerült betölteni.",
  "Couldn't load the cost.": "A költséget nem sikerült betölteni.",
  "Couldn't load the crew.": "A csapatot nem sikerült betölteni.",
  "Couldn't load the impact.": "A következményeket nem sikerült betölteni.",
  "Couldn't load the member list.": "A taglistát nem sikerült betölteni.",
  "Couldn't load the trip's decisions. Reload the page to try again.":
    "Az utazás döntéseit nem sikerült betölteni. Töltsd újra az oldalt.",
  "Couldn't load this board's activity.":
    "A tábla előzményeit nem sikerült betölteni.",
  "Couldn't load this board.": "Ezt a táblát nem sikerült betölteni.",
  "Couldn't load your boards.": "A tábláidat nem sikerült betölteni.",
  "Couldn't load your settings.": "A beállításaidat nem sikerült betölteni.",
  "Couldn't read the deployment.": "A telepítést nem sikerült beolvasni.",
  "Couldn't remove the cover. Please try again.":
    "A borítót nem sikerült eltávolítani. Próbáld újra.",
  "Couldn't remove your picture. Please try again.":
    "A képedet nem sikerült eltávolítani. Próbáld újra.",
  "Couldn't run that lookup.": "A keresést nem sikerült lefuttatni.",
  "Couldn't save that name.": "Ezt a nevet nem sikerült elmenteni.",
  "Couldn't save that. Please try again.":
    "Nem sikerült elmenteni. Próbáld újra.",
  "Couldn't upload that cover. Please try again.":
    "A borítót nem sikerült feltölteni. Próbáld újra.",
  "Couldn't upload that picture. Please try again.":
    "A képet nem sikerült feltölteni. Próbáld újra.",
  "Counting…": "Számolás…",
  "Cover image": "Borítókép",
  "Create account": "Fiók létrehozása",
  "Create board": "Tábla létrehozása",
  "Create link": "Link létrehozása",
  "Create one": "Hozz létre egyet",
  "Creating…": "Létrehozás…",
  Crew: "Csapat",
  Currencies: "Pénznemek",
  Currency: "Pénznem",
  "Danger zone": "Veszélyes műveletek",
  Dates: "Dátumok",
  Decided: "Eldöntve",
  "Decided · {name}": "Eldöntve · {name}",
  "Default currency": "Alapértelmezett pénznem",
  Delete: "Törlés",
  "Delete account…": "Fiók törlése…",
  "Delete board": "Tábla törlése",
  "Delete category": "Sáv törlése",
  "Delete message": "Üzenet törlése",
  "Delete my account": "A fiókom törlése",
  "Delete trip": "Utazás törlése",
  "Delete your account": "Fiókod törlése",
  "Delete “{trip}”?": "Törlöd a(z) „{trip}” utazást?",
  "Deletes the trips owned by {account} and rebuilds the published demo board from the seed: five members, fourteen options, four decisions, the chat and the votes. No other account is touched, and the demo password is reset to the one in the README.":
    "Törli a(z) {account} tulajdonában lévő utazásokat, és újraépíti a nyilvános demó táblát: öt tag, tizennégy javaslat, négy döntés, a csevegés és a szavazatok. Más fiókot nem érint, a demó jelszava pedig visszaáll a README-ben szereplőre.",
  "Deleting your account removes your personal data for good. Boards you own pass to another member, or are deleted if you're the only one on them. The next screen names them before anything happens.":
    "A fiók törlése véglegesen eltávolítja a személyes adataidat. A tulajdonodban lévő táblák átszállnak egy másik tagra, vagy törlődnek, ha egyedül vagy rajtuk. A következő képernyő felsorolja őket, mielőtt bármi történne.",
  "Deleting…": "Törlés…",
  "Deletion impact": "A törlés következményei",
  "Demo data": "Demó adatok",
  "Demo rebuilt.": "A demó újraépült.",
  Destination: "Úti cél",
  Discuss: "Megbeszélés",
  Discussion: "Beszélgetés",
  "Dismiss notification": "Értesítés elvetése",
  "Drag to reorder the {lane} lane": "Fogd meg a(z) {lane} sáv átrendezéséhez",
  "Drag {card} — drop it below to unlock":
    "Fogd meg: {card} — húzd az alatta lévő sávra a feloldáshoz",
  "Drag {card} — reorder it, or drop it above to lock":
    "Fogd meg: {card} — rendezd át, vagy húzd a fölötte lévő sávra a rögzítéshez",
  "Draw the options still being decided, under the ones that are settled.":
    "Mutasd a még eldöntendő javaslatokat is, az eldöntöttek alatt.",
  "Drop here to lock": "Húzd ide a rögzítéshez",
  "Drop here to unlock": "Húzd ide a feloldáshoz",
  "Drop to lock": "Engedd el a rögzítéshez",
  "Drop to unlock": "Engedd el a feloldáshoz",
  Edit: "Szerkesztés",
  "Edit option": "Javaslat szerkesztése",
  "Edit trip": "Utazás szerkesztése",
  "Edit trip details": "Utazás adatainak szerkesztése",
  Email: "E-mail",
  "Email me when I'm @mentioned": "Kapjak e-mailt, ha @megemlítenek",
  "Email queue": "E-mail várólista",
  "Email verified": "E-mail megerősítve",
  "Email, name, or user id": "E-mail, név vagy felhasználói azonosító",
  "End time": "Befejezés időpontja",
  "Ended trip boards": "Befejezett utazások",
  Environment: "Környezet",
  "Everyone on the trip": "Az utazás minden tagja",
  "Everyone on the trip pays a share of this. There is nothing to join and nothing to press.":
    "Az utazás minden tagja fizet belőle egy részt. Nincs mihez csatlakozni, és nincs mit megnyomni.",
  "Everyone on this trip sees the colour you pick.":
    "A választott színt az utazás minden tagja látja.",
  "Exchange rates": "Árfolyamok",
  "Existing links": "Meglévő linkek",
  Failed: "Sikertelen",
  Fetched: "Letöltve",
  Find: "Keresés",
  "Fill in the fields marked with *": "Töltsd ki a *-gal jelölt mezőket",
  "Find a user": "Felhasználó keresése",
  "Full at {cap} options. Remove one to add another.":
    "Betelt, {cap} javaslat van benne. Törölj egyet, ha újat szeretnél.",
  "Give these dates and they'll take their place on the trip. ":
    "Add meg ezeket a dátumokat, és bekerülnek az utazás menetébe. ",
  Global: "Általános",
  "Google only": "Csak Google",
  "Google sign-in didn't complete. Your browser may be blocking cookies set by the API. Try again, or sign in with your email and password.":
    "A Google-bejelentkezés nem fejeződött be. Lehet, hogy a böngésződ blokkolja az API sütijeit. Próbáld újra, vagy jelentkezz be e-mail-címmel és jelszóval.",
  "Group Trip Planner": "Group Trip Planner",
  Guest: "Vendég",
  History: "Lezárva",
  "I'm in": "Én jövök",
  Invite: "Meghívás",
  "It may have been mistyped or truncated by your mail app. Nothing changed. You can turn mention emails off from notification settings instead.":
    "Elképzelhető, hogy elírták, vagy a levelezőprogramod levágta. Semmi nem változott. A megemlítési értesítőket az értesítési beállításokban is kikapcsolhatod.",
  "Joining board…": "Csatlakozás a táblához…",
  "Know them already? The Dates lane will start decided. Skip to let the group vote on it.":
    "Már tudod őket? Akkor a Dátumok sáv eldöntve indul. Hagyd ki, ha a csapat szavazzon róla.",
  Language: "Nyelv",
  "Last seen": "Utoljára láttuk",
  "Leave this trip? You'll lose access unless re-invited.":
    "Kilépsz erről az utazásról? Új meghívó nélkül elveszíted a hozzáférést.",
  "Leave trip": "Kilépés az utazásból",
  "Leave “{trip}”?": "Kilépsz a(z) „{trip}” utazásból?",
  "Leaving…": "Kilépés…",
  Link: "Link",
  "Link type": "Link típusa",
  "Lisbon 2026": "Lisszabon 2026",
  "Lisbon, Portugal": "Lisszabon, Portugália",
  "Load older": "Korábbiak betöltése",
  "Load older messages": "Korábbi üzenetek betöltése",
  "Loading activity…": "Előzmények betöltése…",
  "Loading board…": "Tábla betöltése…",
  "Loading cards…": "Kártyák betöltése…",
  "Loading crew…": "Csapat betöltése…",
  "Loading decisions…": "Döntések betöltése…",
  "Loading lanes…": "Sávok betöltése…",
  "Loading links…": "Linkek betöltése…",
  "Loading messages…": "Üzenetek betöltése…",
  "Loading your boards": "Tábláid betöltése",
  "Loading your boards…": "Tábláid betöltése…",
  "Loading your settings…": "Beállításaid betöltése…",
  "Loading…": "Betöltés…",
  "Lock card": "Kártya rögzítése",
  "Log out": "Kijelentkezés",
  "Looking…": "Keresés…",
  "Make owner": "Tulajdonossá tesz",
  "Make {name} the owner": "{name} legyen a tulajdonos",
  "Mark all read": "Összes megjelölése olvasottként",
  "Mark verified": "Megerősítettnek jelöl",
  "Marked verified.": "Megerősítettnek jelölve.",
  Message: "Üzenet",
  "Message the group… @ to mention": "Írj a csapatnak… @ a megemlítéshez",
  Messages: "Üzenetek",
  "Move to Decided": "Áthelyezés az Eldöntve sávba",
  "Multi-select": "Többszörös választás",
  "Multi-day": "Több napos",
  Mark: "Jel",
  "Mute email": "E-mailek némítása",
  Name: "Név",
  "New board · {step} of {total}": "Új tábla · {step}/{total}",
  "New category name": "Új sáv neve",
  Next: "Tovább",
  "Next month": "Következő hónap",
  "No account? {link}": "Nincs még fiókod? {link}",
  "No committed cost": "Nincs rögzített költség",
  "No dates chosen": "Nincs dátum kiválasztva",
  "No destination yet": "Még nincs úti cél",
  "No feed configured. Conversion is off, and every dashboard reports exact per-currency figures only. This is a valid deployment.":
    "Nincs árfolyamforrás beállítva. Az átváltás ki van kapcsolva, és minden áttekintő csak a pontos, pénznem szerinti összegeket mutatja. Ez érvényes beállítás.",
  "No image yet": "Még nincs kép",
  "No mail has been queued for this account.":
    "Ehhez a fiókhoz nem került levél a várólistára.",
  "No messages yet. Say hello, or @mention someone to pull them in.":
    "Még nincs üzenet. Köszönj be, vagy @említs valakit, hogy bekapcsolódjon.",
  "No need to wait around, though. If someone has already invited you to their board you can join it right now, and propose, vote and chat like everyone else.":
    "Várni viszont nem kell. Ha valaki már meghívott a táblájára, most azonnal csatlakozhatsz, és ugyanúgy javasolhatsz, szavazhatsz és cseveghetsz, mint bárki más.",
  "No options yet": "Még nincs javaslat",
  "No provider key set. Mail is logged to the console, not sent.":
    "Nincs szolgáltatói kulcs beállítva. A levelek a konzolra kerülnek, nem mennek ki.",
  "Nobody matches “{query}”.": "Senki nem felel meg ennek: „{query}”.",
  Node: "Node",
  "Not on the timeline": "Nincs az idővonalon",
  Notes: "Megjegyzések",
  "Nothing has been done from this console yet.":
    "Erről a konzolról még semmi nem történt.",
  "Nothing has happened here yet. Locked decisions, role changes, and departures will show up on this list.":
    "Itt még semmi nem történt. A rögzített döntések, szerepváltások és kilépések ezen a listán jelennek meg.",
  "Nothing here has dates yet. Add dates to a decision and it will appear on the trip's calendar.":
    "Itt még semminek nincs dátuma. Adj dátumot egy döntéshez, és megjelenik az utazás naptárában.",
  "Nothing is decided yet. Lock an option on the board and it lands here.":
    "Még semmi nincs eldöntve. Rögzíts egy javaslatot a táblán, és ide kerül.",
  "Nothing was decided here": "Itt nem dőlt el semmi",
  "Nothing yet. Proposals, decisions and mentions land here.":
    "Még semmi. A javaslatok, döntések és megemlítések ide kerülnek.",
  "Notification settings": "Értesítési beállítások",
  Notifications: "Értesítések",
  "Nowhere booked for this night": "Erre az éjszakára nincs szállás",
  Off: "Ki",
  "Offline, not updating": "Nincs kapcsolat, nem frissül",
  On: "Be",
  "One thing first: starting a board needs a confirmed email address. We've sent a link to {email}. Open it and you're set. (Check the spam folder if it's taking its time.)":
    "Egy dolog még: tábla indításához megerősített e-mail-cím kell. Küldtünk egy linket ide: {email}. Nyisd meg, és készen vagy. (Ha késik, nézd meg a spam mappát is.)",
  "Only people who opt in": "Csak aki jelentkezik rá",
  "Operations · signed in as {email}": "Üzemeltetés · bejelentkezve: {email}",
  "Operator log": "Üzemeltetői napló",
  Options: "Javaslatok",
  "Outside the trip's dates": "Az utazás dátumain kívül",
  "Over budget": "Túllépi a keretet",
  "Overlaps another {lane} decision":
    "Átfedésben van egy másik {lane} döntéssel",
  "Ownership transfers ({n})": "Tulajdonjog átszáll ({n})",
  Palettes: "Színpaletták",
  Password: "Jelszó",
  Pending: "Várakozik",
  "Per person": "Fejenként",
  "Permanently deleted ({n})": "Véglegesen törölve ({n})",
  Personal: "Személyes",
  "Pick both days, or skip this step.":
    "Válaszd ki mindkét napot, vagy hagyd ki ezt a lépést.",
  Plan: "Terv",
  "Previous month": "Előző hónap",
  "Priced for": "Az ára erre szól:",
  "Pick a mark to wear it in this colour.":
    "Válassz egy jelet, hogy ebben a színben viselhesd.",
  "Priced for part of the group": "A csapat egy részére szóló ár",
  "Profile picture": "Profilkép",
  Progress: "Állapot",
  "Propose an option": "Javaslat beküldése",
  "Propose option": "Javaslat beküldése",
  Proposed: "Javasolva",
  "Proposed by": "Beküldte",
  Published: "Közzétéve",
  "React {emoji}": "Reakció: {emoji}",
  "Reading the deployment…": "A telepítés beolvasása…",
  "Reading…": "Beolvasás…",
  "Rebuild the demo trip": "Demó utazás újraépítése",
  "Rebuilding…": "Újraépítés…",
  "Redeeming your invite.": "Meghívó beváltása.",
  Refresh: "Frissítés",
  Reload: "Újratöltés",
  "Reload the board": "Tábla újratöltése",
  Remove: "Eltávolítás",
  "Remove from trip": "Eltávolítás az utazásból",
  "Remove {name} and block them from rejoining":
    "{name} eltávolítása és kizárása az újracsatlakozásból",
  "Remove {name} from the trip": "{name} eltávolítása az utazásból",
  "Removing…": "Eltávolítás…",
  "Rename {lane}": "{lane} átnevezése",
  "Reorder {trip}": "{trip} átrendezése",
  Replaced: "Lecserélve",
  "Resend verification": "Megerősítő levél újraküldése",
  Retry: "Újra",
  "Role granted": "Szerep megadva",
  Save: "Mentés",
  "Save changes": "Módosítások mentése",
  "Save option": "Javaslat mentése",
  "Saved. Everyone on your boards sees the new name.":
    "Elmentve. A tábláidon mindenki az új nevet látja.",
  "Saving…": "Mentés…",
  Send: "Küldés",
  Sending: "Küldés folyamatban",
  Sent: "Elküldve",
  "Set {name} as {role}": "{name} legyen {role}",
  Settings: "Beállítások",
  "Show proposals": "Javaslatok mutatása",
  "Showing the first {n} day. Something is dated much further out than the rest.":
    "Csak az első {n} napot mutatjuk. Valami sokkal későbbre van dátumozva, mint a többi.",
  "Showing the first {n} days. Something is dated much further out than the rest.":
    "Csak az első {n} napot mutatjuk. Valami sokkal későbbre van dátumozva, mint a többi.",
  "Sign in": "Bejelentkezés",
  "Sign-in": "Bejelentkezés",
  "Signed up": "Regisztrált",
  "Signing in…": "Bejelentkezés…",
  "Single-select": "Egyszeres választás",
  Skip: "Kihagyom",
  "Some of these fall outside the trip's own dates.":
    "Ezek közül néhány az utazás dátumain kívül esik.",
  Someone: "Valaki",
  "Someone naming you in a board's chat sends you an email. Turn this off and mentions still show up in the app.":
    "Ha valaki megnevez egy tábla csevegésében, e-mailt kapsz róla. Ha kikapcsolod, a megemlítések akkor is megjelennek az alkalmazásban.",
  "Something broke on this page": "Valami elromlott ezen az oldalon",
  "Something went wrong": "Valami hiba történt",
  Source: "Forrás",
  "Still to spend": "Még elkölthető",
  "Start time": "Kezdés időpontja",
  Target: "Cél",
  "That board doesn't exist or you're not a member.":
    "Ez a tábla nem létezik, vagy nem vagy a tagja.",
  "That didn't work.": "Ez nem sikerült.",
  "That link didn't work": "Ez a link nem működött",
  "That start date has already passed.": "Ez a kezdődátum már elmúlt.",
  "That's further ahead than a trip can be planned.":
    "Ez messzebb van, mint ameddig egy utazás előre tervezhető.",
  "The Dates lane starts with this already decided. Unlock it any time to let the group pick instead.":
    "A Dátumok sáv ezzel eldöntve indul. Bármikor feloldhatod, és akkor a csapat dönt.",
  "The card gets an {control} button, and its cost is split between the people who press it. Nobody else pays for it, and everyone can see who is in.":
    "A kártyára kerül egy {control} gomb, és a költséget azok osztják el, akik megnyomják. Más nem fizet érte, és azt is látja mindenki, ki jön.",
  "The error has been recorded. Reloading usually clears it. Your trips and decisions are stored on the server, so nothing was lost.":
    "A hibát rögzítettük. Az újratöltés általában megoldja. Az utazásaid és döntéseid a szerveren vannak, tehát semmi nem veszett el.",
  "The last day can't come before the first.":
    "Az utolsó nap nem lehet korábban, mint az első.",
  "This app is in {language}. It is the only language available so far.":
    "Ez az alkalmazás {language} nyelven van. Egyelőre csak ez a nyelv érhető el.",
  "This board changed since you opened it. Reload to see the latest, then re-apply your edit.":
    "Ez a tábla megváltozott, mióta megnyitottad. Töltsd újra a legfrissebb állapothoz, majd írd be újra a módosításodat.",
  "This board has ended and is now read-only. Proposing, dot-voting, and locking are closed.":
    "Ez a tábla lezárult, és mostantól csak olvasható. A javaslás, a szavazás és a rögzítés le van zárva.",
  "This deployment": "Ez a telepítés",
  "This deployment has no console configured for you.":
    "Ebben a telepítésben nincs konzol beállítva neked.",
  "This is the decision. The trip's dates go with it.":
    "Ez a döntés. Az utazás dátumai is eltűnnek vele.",
  "This is the decision. The lane goes back to undecided.":
    "Ez a döntés. A sáv visszatér az eldöntetlen állapotba.",
  "This lane wasn’t changed": "A sáv nem változott",
  "This link is invalid or has expired. Sign in to request a new one.":
    "Ez a link érvénytelen vagy lejárt. Jelentkezz be, és kérj újat.",
  "This permanently deletes your account and personal data. It can't be undone.":
    "Ez véglegesen törli a fiókodat és a személyes adataidat. Nem vonható vissza.",
  "This permanently removes the board and its membership for everyone. This can't be undone.":
    "Ez véglegesen törli a táblát és mindenki tagságát. Nem vonható vissza.",
  "This throws away whatever visitors have done to the demo, and cannot be undone.":
    "Ez eldobja mindazt, amit a látogatók a demóval tettek, és nem vonható vissza.",
  "This trip's dates aren't settled yet, so the days below are drawn from the options themselves and will shift as they change. Lock a date to frame the trip.":
    "Az utazás dátumai még nincsenek eldöntve, ezért az alábbi napok magukból a javaslatokból adódnak, és velük együtt mozdulnak. Rögzíts egy dátumot, hogy az utazás keretet kapjon.",
  Timeline: "Idővonal",
  Title: "Cím",
  "To silence a single noisy board, open it and use {control} in its ⋯ menu.":
    "Ha egyetlen zajos táblát szeretnél elhallgattatni, nyisd meg, és használd a {control} lehetőséget a ⋯ menüjében.",
  "Total for the group": "A csapat összköltsége",
  "Transfer ownership": "Tulajdonjog átadása",
  Trip: "Utazás",
  "Trip Board": "Utazástábla",
  "Trip Board — your boards": "Utazástábla — a tábláid",
  "Trip chat": "Utazás csevegése",
  "Trip menu": "Utazás menü",
  "Trip view": "Nézet",
  "Trip name": "Utazás neve",
  Trips: "Utazások",
  "Try again": "Próbáld újra",
  Unblock: "Kitiltás visszavonása",
  Unlock: "Feloldás",
  Unverified: "Nem megerősített",
  "Up since": "Fut ekkortól",
  "Uploading…": "Feltöltés…",
  Uploads: "Feltöltések",
  Users: "Felhasználók",
  "Verification email sent.": "Megerősítő levél elküldve.",
  "Verification failed": "A megerősítés nem sikerült",
  Verified: "Megerősítve",
  "Verifying…": "Megerősítés…",
  "View details": "Részletek",
  Volume: "Mennyiség",
  Votes: "Szavazatok",
  "We won't email you when someone @mentions you. You'll still see mentions in the app, and account emails like verifying your address or signing in are unaffected.":
    "Nem küldünk e-mailt, ha valaki @megemlít. A megemlítéseket az alkalmazásban továbbra is látod, és ez nem érinti a fiókkal kapcsolatos leveleket, például a cím megerősítését vagy a bejelentkezést.",
  "What are prices quoted in?": "Milyen pénznemben vannak az árak?",
  "What's the trip called?": "Mi az utazás neve?",
  When: "Mikor",
  "When?": "Mikor?",
  "Where are you going?": "Hová mentek?",
  "Yes, rebuild it": "Igen, épüljön újra",
  "You don't own any boards.": "Nincs saját táblád.",
  "You're unsubscribed": "Leiratkoztál",
  "Your picture": "A képed",
  "Your settings": "A beállításaid",
  "Your trip boards": "Az utazástábláid",
  "barred from rejoining": "nem csatlakozhat újra",
  "email, name, or user id": "e-mail, név vagy felhasználói azonosító",
  "hh:mm": "óó:pp",
  "https://…": "https://…",
  in: "jön",
  "just now": "épp most",
  "message deleted": "üzenet törölve",
  "no bed booked": "nincs lefoglalt szállás",
  "no rate to add these up with":
    "nincs árfolyam, amivel ezeket összeadhatnánk",
  "no votes": "nincs szavazat",
  "nobody yet": "még senki",
  "not sent": "nincs elküldve",
  "nothing planned": "nincs terv",
  "nothing, there was no demo trip here": "semmit, itt nem volt demó utazás",
  or: "vagy",
  "outside the trip's dates": "az utazás dátumain kívül",
  "per person": "fejenként",
  over: "túllépés",
  "to spare": "marad",
  "voted before the last change": "a legutóbbi módosítás előtt szavazott",
  "your address": "a címed",
  "yours: ": "a tiéd: ",
  "{actor} deleted {author}'s message": "{actor} törölte {author} üzenetét",
  "{amount} per person": "{amount} fejenként",
  "{cap} categories is the maximum. Delete one to add another.":
    "Legfeljebb {cap} sáv lehet. Törölj egyet, ha újat szeretnél.",
  "{card} — edit option": "{card} — javaslat szerkesztése",
  "{card} — view details": "{card} — részletek",
  "{currencies} not converted": "{currencies} nincs átváltva",
  "{currencies} not counted": "{currencies} nincs beszámítva",
  "{currencies} not counted: no rate to convert with":
    "{currencies} nincs beszámítva: nincs árfolyam az átváltáshoz",
  "{date}: {count}": "{date}: {count}",
  "{emoji} {n}": "{emoji} {n}",
  "{label} — choose a file": "{label} — válassz fájlt",
  "{lane} lane actions": "{lane} sáv műveletei",
  "{lane} — rename category": "{lane} — sáv átnevezése",
  "{name} deleted their message": "{name} törölte a saját üzenetét",
  "{n} attempt": "{n} kísérlet",
  "{n} attempts": "{n} kísérlet",
  "{n} decision pending": "{n} döntés várakozik",
  "{n} decision placed": "{n} döntés elhelyezve",
  "{n} decisions pending": "{n} döntés várakozik",
  "{n} decisions placed": "{n} döntés elhelyezve",
  "{n} in": "{n} jön",
  "{n} in — see who": "{n} jön — nézd meg, kik",
  "{n} job claimed longer ago than the reclaim window. A worker probably died mid-send.":
    "{n} feladat régebben van lefoglalva, mint a visszaigénylési idő. Valószínűleg elhalt egy feldolgozó küldés közben.",
  "{n} jobs claimed longer ago than the reclaim window. A worker probably died mid-send.":
    "{n} feladat régebben van lefoglalva, mint a visszaigénylési idő. Valószínűleg elhalt egy feldolgozó küldés közben.",
  "{n} member": "{n} tag",
  "{n} members": "{n} tag",
  "{n} night": "{n} éjszaka",
  "{n} nights": "{n} éjszaka",
  "{n} signups in the last 30 days": "{n} regisztráció az elmúlt 30 napban",
  "{n} unread": "{n} olvasatlan",
  "{n} vote — see who": "{n} szavazat — nézd meg, kik",
  "Everyone has voted.": "Mindenki szavazott.",
  "Everyone is in.": "Mindenki benne van.",
  "Not in yet": "Még nem jelezte",
  "Yet to vote": "Még nem szavazott",
  "{n} / {total} in": "{n} / {total} benne",
  "{n} / {total} voted": "{n} / {total} szavazott",
  "{n} voted": "{n} szavazott",
  "{n} votes — see who": "{n} szavazat — nézd meg, kik",
  "{trip} (you're the only member)": "{trip} (egyedül te vagy a tagja)",
  "{trip} chat": "{trip} csevegése",
  "{trip} chat, {n} unread": "{trip} csevegése, {n} olvasatlan",
  "· outside the trip’s dates": "· az utazás dátumain kívül",
  "— exactly {amount}": "— pontosan {amount}",
  "○ Vote": "○ Szavazok",
  "● Voted": "● Megszavaztam",
  "☀ Light mode": "☀ Világos mód",
  "☾ Dark mode": "☾ Sötét mód",
  "⚙ Console": "⚙ Konzol",
  "＋ Add category": "＋ Új sáv",
  "＋ New board": "＋ Új tábla",
  "＋ Propose the first option": "＋ Küldd be az első javaslatot",
  "Make {name} the owner? You'll become a co-organizer, and only they can hand it back.":
    "Legyen {name} a tulajdonos? Te társszervező leszel, és csak ő adhatja vissza.",
  "Remove and block": "Eltávolítás és tiltás",
  "Remove {name} and block them? They won't be able to rejoin, even with an invite link.":
    "Eltávolítod és letiltod őt: {name}? Nem tud majd visszalépni, meghívó linkkel sem.",
  "Remove {name} from this trip? You can invite them back.":
    "Eltávolítod őt az útról: {name}? Később újra meghívhatod.",
  "Role for {name}": "{name} szerepköre",
  "They lose access and can't rejoin, even with a link.":
    "Elveszíti a hozzáférést, és linkkel sem tud visszalépni.",
  "They lose access. You can invite them back.":
    "Elveszíti a hozzáférést. Később újra meghívhatod.",
  "They take over the trip and you become a co-organizer.":
    "Ő veszi át az utat, te pedig társszervező leszel.",
  "Nothing found. You can write it in yourself.":
    "Nincs találat. Beírhatod magad is.",
  "Start typing to search, or write anywhere you like.":
    "Kezdj írni a kereséshez, vagy írj be bármit.",
  "Place names from {source}, CC BY 4.0": "Helynévadatok: {source}, CC BY 4.0",
  "Place list": "Helyek listája",
  "Loads the destination suggestions from the dataset shipped with this build: every populated place over 5,000 people, every region and every country. Needed once per environment; nothing else uses it and nothing depends on it, so re-running is safe. Until it has run, the destination field on the create-trip form simply offers nothing.":
    "Betölti az úticél-javaslatokat a buildhez csomagolt adathalmazból: minden 5000 főnél nagyobb települést, minden régiót és országot. Környezetenként egyszer kell; semmi más nem használja és semmi nem függ tőle, így újra futtatni is biztonságos. Amíg le nem fut, az új utazás űrlap úticél mezője nem kínál semmit.",
  "Loading places…": "Helyek betöltése…",
  "Load the place list": "Helyek listájának betöltése",
  "Writing tens of thousands of rows. This takes a few seconds.":
    "Tízezernyi sor írása. Ez elég néhány másodpercet vesz igénybe.",
  "Places loaded.": "A helyek betöltődtek.",
  Places: "Helyek",
  "Account suspended.": "A fiók felfüggesztve.",
  "Ends on": "Eddig tart",
  "Lift suspension": "Felfüggesztés feloldása",
  Permanent: "Végleges",
  "Pick an end date, or choose permanent.":
    "Válassz záró dátumot, vagy jelöld véglegesnek.",
  "Reason given": "Megadott indok",
  "Say why. The person is shown this.":
    "Írd le az indokot. Ezt látja majd az érintett.",
  Suspend: "Felfüggesztés",
  "Suspend account": "Fiók felfüggesztése",
  Suspended: "Felfüggesztve",
  "Suspended until": "Felfüggesztve eddig",
  "Suspending…": "Felfüggesztés…",
  "Suspension lifted.": "A felfüggesztés feloldva.",
  "Was suspended": "Fel volt függesztve",
  "Was suspended until": "Eddig volt felfüggesztve",
  "Why this account is being suspended": "Miért függeszted fel ezt a fiókot",
  "Any trip they own passes to a co-organizer, or to the longest-standing participant. A trip with nobody else on it is deleted, with everything in it.":
    "A saját utazásai átszállnak egy társszervezőre, vagy a leghosszabb ideje csatlakozott résztvevőre. Az az utazás, amelyen rajta kívül nincs senki, mindenestül törlődik.",
  "Delete account": "Fiók törlése",
  "Erasing…": "Törlés…",
  "Their proposals and messages in other people's trips stay, credited to “Deleted user”. This cannot be undone.":
    "A más utazásaiban tett javaslatai és üzenetei megmaradnak, „Deleted user” néven. Ez nem vonható vissza.",
  "They owned no trips.": "Nem volt saját utazása.",
  "Yes, erase this account": "Igen, töröljük ezt a fiókot",
  "{email} is erased.": "{email} törölve.",
  "{trip} → {name}": "{trip} → {name}",
  "{trip} (deleted)": "{trip} (törölve)",
  "Delete “{lane}”?": "Törlöd a(z) „{lane}” sávot?",
  "This removes the lane and every card in it. This can’t be undone.":
    "Ez eltávolítja a sávot és minden kártyáját. Ez nem vonható vissza.",
  "Crew — manage members and roles": "Csapat — tagok és szerepkörök kezelése",
  "Crew — see members and roles": "Csapat — tagok és szerepkörök megtekintése",
  "Guests: not asked to vote": "Vendégek: őket nem kérdezzük",
  "Guests: not asked to join": "Vendégek: ők nem csatlakoznak",
  Lane: "Sáv",
  "Propose something at {time} on {day}": "Javasolj valamit ide: {day} {time}",
  "Still being decided": "Még döntés alatt",
  "No dates yet": "Még nincs dátum",
  "No price yet": "Még nincs ár",
  "split between whoever’s in": "a résztvevők között elosztva",
  "for {n} person on the trip": "{n} főre az utazáson",
  "for {n} people on the trip": "{n} főre az utazáson",
  "edited since": "azóta szerkesztve",
  "Nobody has voted for this yet.": "Erre még senki nem szavazott.",
  "Nobody is in yet.": "Még senki sem jelentkezett.",
  "Who’s in": "Ki tart velünk",
  "outside the trip’s dates": "az utazás dátumain kívül",
  "A lowercase letter": "Egy kisbetű",
  "A number": "Egy számjegy",
  "A special character": "Egy speciális karakter",
  "An uppercase letter": "Egy nagybetű",
  "At least {n} characters": "Legalább {n} karakter",
  "Done:": "Kész:",
  "Hide password": "Jelszó elrejtése",
  Nickname: "Becenév",
  "No sign of it? Have a look in your spam folder. It likes to hide there.":
    "Nem találod? Nézd meg a spam mappát is. Szeret ott megbújni.",
  Normal: "Közepes",
  "Password again": "Jelszó még egyszer",
  "Show password": "Jelszó megjelenítése",
  "Still needed:": "Még hiányzik:",
  Strong: "Erős",
  "We've sent you a link to verify your email address.":
    "Küldtünk egy linket az e-mail-címed megerősítéséhez.",
  Weak: "Gyenge",
  "Your password needs": "A jelszavadhoz kell",
  "Welcome on board! :)": "Üdv a fedélzeten! :)",
  "Pick a day": "Válassz egy napot",
  "One day. Pick a later one to stretch it.":
    "Egy nap. Válassz egy későbbit, ha hosszabb.",
  "Pick any day to start again": "Bármelyik napra kattintva kezdheted újra",
  Organizer: "Szervező",
  Traveler: "Utazó",
  "runs the trip with you, adding lanes, inviting people and locking in decisions.":
    "veled együtt szervezi az utazást, sávokat ad hozzá, másokat hív meg, és rögzíti a döntéseket.",
  "comes along, suggesting options, voting on everything and joining the chat.":
    "ő is jön, javaslatokat tesz, mindenre szavaz, és beszélget a többiekkel.",
  "just looks, and can do nothing else.": "csak nézelődik, mást nem tehet.",
  "{kind}: {blurb}": "{kind}: {blurb}",
  "{kind}: anyone with the link can join.":
    "{kind}: bárki csatlakozhat, akinek megvan a link.",
  "Show me around": "Mutasd meg a programot",
  "Skip the tour": "Kihagyom a bemutatót",
  "Let's go": "Vágjunk bele",
  "{step} of {total}": "{step} / {total}",
  "One lane, one question": "Egy sáv, egy kérdés",
  "Every column is something the group has to agree on: when to go, how to get there, where to sleep. Add as many as your trip needs.":
    "Minden oszlop egy kérdés, amiben meg kell egyezni: mikor induljatok, mivel menjetek, hol aludjatok. Annyit veszel fel, amennyire szükség van.",
  "Anyone can suggest something": "Bárki javasolhat valamit",
  "Are you sure?": "Biztos vagy benne?",
  "Drop an idea into a lane with a price, a link and the dates it runs. You are not asking permission. You are putting it on the table.":
    "Dobj be egy ötletet a sávba árral, linkkel és időponttal. Nem engedélyt kérsz. Leteszed az asztalra.",
  "Everyone votes": "Mindenki szavaz",
  "Say what you think of each idea and see at a glance who agrees. When the group has made up its mind, an organizer locks the winner in and it stays at the top of its lane.":
    "Mondd el, mit gondolsz az ötletekről, és láthatod, ki ért egyet. Ha megvan a döntés, egy szervező rögzíti a győztest, és az a sáv tetején marad.",
  "The money adds itself up": "A költségek maguktól összeadódnak",
  "Every decision you lock in lands here, split per person. Give the trip a target and this will tell you where you stand against it.":
    "Minden rögzített döntés ide kerül, fejenkénti bontásban. Adj meg egy keretet, és megmutatja, hol tartotok hozzá képest.",
  "Two ways to look at it": "Kétféleképpen nézheted",
  "Plan is the board you have been looking at. Timeline lays the same decisions out day by day, so you can see what your trip actually looks like.":
    "A Terv az a tábla, amit eddig néztél. Az Idővonal ugyanazokat a döntéseket napokra bontva mutatja, így látod, hogy fest az utazás.",
  "Who you're going with": "Kikkel utaztok",
  "Everyone on the trip, and what each of them can do. Organizers lock decisions in; travelers propose and vote.":
    "Mindenki, aki jön, és hogy ki mit tehet. A szervezők rögzítik a döntéseket, az utazók javasolnak és szavaznak.",
  "Bring the others in": "Hívd meg a többieket",
  "One link is all it takes, with no app for them to install. You choose what each link lets someone do.":
    "Elég egyetlen link, és nekik semmit sem kell telepíteniük. Te döntöd el, mit tehet, aki vele érkezik.",
  "Talk it over here": "Itt beszéljétek meg",
  "Every lane gets its own conversation, so the reason behind a decision stays next to the decision instead of scrolling away in a group chat.":
    "Minden sávnak saját beszélgetése van, így a döntés indoklása a döntés mellett marad, nem vész el egy csoportos csevegésben.",
  "A board is one trip": "Egy tábla egy utazás",
  "Start one here. The dates, the flights, the bill, the arguing: everything about that trip lives on its own board.":
    "Itt hozhatsz létre egyet. Az időpont, a repülőjegy, a számla, a vita: az utazás minden része a saját tábláján él.",
  "Everything else is in here": "Minden más itt található",
  "Your picture, the app's language, and this tour again whenever you want it.":
    "A képed, az alkalmazás nyelve, és ez a bemutató, amikor csak újra szeretnéd.",
  "Let the fun begin!": "Kezdődjön a móka!",
  "That's the whole thing. Go and plan something.":
    "Ennyi az egész. Menj, és tervezz valamit.",
  "Choose your circle": "Válaszd ki a kört",
  "Couldn't set that picture. Please try again.":
    "Nem sikerült beállítani a képet. Próbáld újra.",
  "Drag the picture to move it, and use the slider to zoom.":
    "Húzd a képet a mozgatáshoz, a csúszkával pedig nagyíthatsz.",
  "Position your picture": "Igazítsd be a képet",
  "That file couldn't be read as a picture.":
    "Ezt a fájlt nem sikerült képként megnyitni.",
  "That picture couldn't be cropped here. Try another one.":
    "Ezt a képet itt nem sikerült levágni. Próbálj egy másikat.",
  Zoom: "Nagyítás",
  "A link has to start with http:// or https://":
    "A linknek http:// vagy https:// előtaggal kell kezdődnie",
  "A personal link needs the address it is for.":
    "A személyes linkhez meg kell adni a címzett e-mail-címét.",
  "That link is too long.": "Ez a link túl hosszú.",
  "That's {n} characters too long. The notes hold {max}.":
    "Ez {n} karakterrel hosszabb a megengedettnél. A jegyzet {max} karaktert tárol.",
  "We'll email the link, and only this address can use it.":
    "Elküldjük a linket e-mailben, és csak ez a cím használhatja.",
  "{kind}: for one address, and only that address.":
    "{kind}: egyetlen címre, és csak arra.",
  "{n}/{max}": "{n}/{max}",
  "All conversations": "Összes beszélgetés",
  Conversations: "Beszélgetések",
  "No boards to talk on yet.": "Még nincs tábla, ahol beszélgethetnél.",
  "Invite people": "Hívj meg másokat",
  "Unmute email": "E-mailek visszakapcsolása",
  "Email muted": "E-mailek némítva",
  "No links to show. Create one above.": "Nincs megjeleníthető link. Készíts egyet fent.",
  "The talking goes with you": "A beszélgetés veled tart",
  "Chat is here on every page, not just inside one board. You will have someone to talk to once you make a trip or join one.": "A csevegés minden oldalon itt van, nem csak egy táblán belül. Akkor lesz kivel beszélgetned, ha létrehozol egy utat vagy csatlakozol egyhez.",
  "Now make one": "Most készíts egyet",
  "Create your first trip and I will show you around the board itself.": "Hozd létre az első utadat, és körbevezetlek magán a táblán is.",
  "Previous colour": "Előző szín",
  "Next colour": "Következő szín",
  "Previous mark": "Előző jel",
  "Next mark": "Következő jel",
  "Replace your photo?": "Lecseréled a fotódat?",
  "A drawn avatar takes the place of your uploaded picture, and the picture is deleted. You can always upload another one.": "A rajzolt avatar a feltöltött képed helyére lép, a képet pedig töröljük. Bármikor feltölthetsz egy újat.",
  "Use a drawn avatar": "Rajzolt avatart használok",
  "Keep my photo": "Marad a fotóm",
};
